version: '3'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    command: sh -c "npm run start"
    ports:
      - "3000:3000"
    tty: true
    networks:
      - travel

networks:
  travel:
    external: true